CREATE TABLE IF NOT EXISTS statistics
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uri       VARCHAR     NOT NULL,
    app       VARCHAR     NOT NULL,
    ip        VARCHAR(16) NOT NULL,
    timestamp TIMESTAMP   NOT NULL
);