spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-server
  config:
    import: "configserver:"

  cloud:
    config:
      discovery:
        service-id: config-server
        enabled: true
      fail-fast: true
      retry:
        useRandomPolicy: true
        max-interval: 6000

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/