spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: main_service_route
          uri: lb://main-service
          predicates:
            - Path=/categories/**,/users/**,/comments/**,/events/**,/compilations/**,/admin/**

server:
  port: 8080